<?php
if(isset($_POST['UpdateProduct'])){
include('DatabaseControl/dbConnect.php');
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://partner-gateway-staging.mjplatform.com//v1/catalog?category_id=4");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


$headers = array();
$headers[] = "Accept: application/json";
$headers[] = "Content-Type: application/json";
$headers[] = "X-Mjf-Api-Key: 97f3f67d-0dc2-11e8-a2fc-02c828cd9332";
$headers[] = "X-Mjf-Organization-Id: 9";
$headers[] = "X-Mjf-Facility-Id: 21";
$headers[] = "X-Mjf-User-Id: 58";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$arr=json_decode($result);
echo "<pre>";
print_r($arr);exit;
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
foreach($arr as $a)
{
	#print_r($a);
	#echo "Test";
	#echo "INSERT INTO `mj_freeway_products` (`api_id`, `name`, `item_number`, `description`, `available_online`, `category_id`, `category_name`, `subcategory_id`, `subcategory_name`, `strain_id`, `strain_name`, `created_at`, `updated_at`, `pricing_type`, `in_stock`, `default_price`, `pricing_group_id`, `size`, `url`, `size2`, `url2`, `size3`, `url3`, `size4`, `url4`, `size5`, `url5`, `size6`, `url6`, `size7`, `url7`) VALUES ( '".$a->id."', '".$a->name."', '".$a->item_number."', '".$a->description."', '".$a->available_online."', '".$a->category_id."', '".$a->category_name."', '".$a->subcategory_id."', '".$a->subcategory_name."', '".$a->strain_id."', '".$a->strain_name."', '".$a->created_at."', '".$a->updated_at."', '".$a->pricing_type."', '".$a->in_stock."', '".$a->pricing->default_price."', '".$a->pricing->pricing_group_id."', '".$a->primary_image_urls[0]->size."', '".$a->primary_image_urls[0]->url."', '".$a->primary_image_urls[1]->size."', '".$a->primary_image_urls[1]->url."', '".$a->primary_image_urls[2]->size."', '".$a->primary_image_urls[2]->url."', '".$a->primary_image_urls[3]->size."', '".$a->primary_image_urls[3]->url."', '".$a->primary_image_urls[4]->size."', '".$a->primary_image_urls[4]->url."', '".$a->primary_image_urls[5]->size."', '".$a->primary_image_urls[5]->url."', '".$a->primary_image_urls[6]->size."', '".$a->primary_image_urls[6]->url."');";
	$check=mysql_num_rows(mysql_query("SELECT * FROM `mj_freeway_products` WHERE `api_id`='".$a->id."'"));
	if($check==0)
	{
		
		mysql_query("INSERT INTO `mj_freeway_products` (`api_id`, `name`, `item_number`, `description`, `available_online`, `category_id`, `category_name`, `subcategory_id`, `subcategory_name`, `strain_id`, `strain_name`, `created_at`, `updated_at`, `pricing_type`, `in_stock`, `default_price`, `pricing_group_id`, `size`, `url`, `size2`, `url2`, `size3`, `url3`, `size4`, `url4`, `size5`, `url5`, `size6`, `url6`, `size7`, `url7`) VALUES ( '".$a->id."', '".$a->name."', '".$a->item_number."', '".$a->description."', '".$a->available_online."', '".$a->category_id."', '".$a->category_name."', '".$a->subcategory_id."', '".$a->subcategory_name."', '".$a->strain_id."', '".$a->strain_name."', '".$a->created_at."', '".$a->updated_at."', '".$a->pricing_type."', '".$a->in_stock."', '".$a->pricing->default_price."', '".$a->pricing->pricing_group_id."', '".$a->primary_image_urls[0]->size."', '".$a->primary_image_urls[0]->url."', '".$a->primary_image_urls[1]->size."', '".$a->primary_image_urls[1]->url."', '".$a->primary_image_urls[2]->size."', '".$a->primary_image_urls[2]->url."', '".$a->primary_image_urls[3]->size."', '".$a->primary_image_urls[3]->url."', '".$a->primary_image_urls[4]->size."', '".$a->primary_image_urls[4]->url."', '".$a->primary_image_urls[5]->size."', '".$a->primary_image_urls[5]->url."', '".$a->primary_image_urls[6]->size."', '".$a->primary_image_urls[6]->url."');");
		if($a->primary_image_urls[0]->url!="")
		{
			$id=mysql_insert_id();
			$imageName="mj_free_way-".$id.".png";
			copy($a->primary_image_urls[0]->url,"../admin/product_images/".$imageName);
			mysql_query("UPDATE `mj_freeway_products` SET `orignal_image`='".$imageName."' WHERE `id`='".$id."'");
		}
	}
	else
	{
		mysql_query("UPDATE `mj_freeway_products` SET `name`='".$a->name."', `item_number`='".$a->item_number."', `description`='".$a->description."', `available_online`='".$a->available_online."', `category_id`='".$a->category_id."', `category_name`='".$a->category_name."', `subcategory_id`='".$a->subcategory_id."', `subcategory_name`='".$a->subcategory_name."', `strain_id`='".$a->strain_id."', `strain_name`='".$a->strain_name."', `created_at`='".$a->created_at."', `updated_at`='".$a->updated_at."', `pricing_type`='".$a->pricing_type."', `in_stock`='".$a->in_stock."', `default_price`='".$a->pricing->default_price."', `pricing_group_id`='".$a->pricing->pricing_group_id."', `size`='".$a->primary_image_urls[0]->size."', `url`='".$a->primary_image_urls[0]->url."', `size2`='".$a->primary_image_urls[1]->size."', `url2`='".$a->primary_image_urls[1]->url."', `size3`='".$a->primary_image_urls[2]->size."', `url3`='".$a->primary_image_urls[2]->url."', `size4`='".$a->primary_image_urls[3]->size."', `url4`='".$a->primary_image_urls[3]->url."', `size5`='".$a->primary_image_urls[4]->size."', `url5`='".$a->primary_image_urls[4]->url."', `size6`='".$a->primary_image_urls[5]->size."', `url6`='".$a->primary_image_urls[5]->url."', `size7`='".$a->primary_image_urls[6]->size."', `url7`='".$a->primary_image_urls[6]->url."' WHERE `api_id`='".$a->id."'");
		if($a->primary_image_urls[0]->url!="")
		{
			$getId=mysql_fetch_array(mysql_query("SELECT `id` FROM `mj_freeway_products` WHERE `api_id`='".$a->id."' "));
			$imageName="mj_free_way-".$getId['id'].".png";
			copy($a->primary_image_urls[0]->url,"../admin/product_images/".$imageName);
			mysql_query("UPDATE `mj_freeway_products` SET `orignal_image`='".$imageName."' WHERE `id`='".$getId['id']."'");
		}
	}
	
	
#exit();
}
}
header('Location: index.php?action=product_mj_freeway_list');

?>